name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  run_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Installing dependencies
        run: npm i
      - name: Run test
        run: npm test
