name: Backend CI

on:
  push:
    branches:
      - main


jobs:
  run_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Setup Node.js
        uses: actions/setup-node
      -name: Installing dependencies
        run: npm i
      -name: Run test
        run: npm test
      